openapi: 3.0.0
info:
  title: Démo Design-first du service web de billetterie de concerts
  version: 0.0.1
servers:
- url: http://localhost:5001
paths:
  /:
    summary: Accueil du service de billeterie
    get:
      summary: Obtenir les informations sur le service de billeterie
      description: ""
      operationId: ""
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Default
  /concerts:
    summary: La liste des concerts à venir
    get:
      tags:
      - Concerts
      summary: Obtenir la liste des concerts à venir
      description: ""
      operationId: getAllConcerts
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/concerts'
      x-swagger-router-controller: Concerts
  /concerts/{id}:
    summary: Le détail d'un concert
    get:
      tags:
      - Concerts
      summary: Obtenir le détail d'un concert
      description: ""
      operationId: ""
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          minimum: 0
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/concert-detail'
          links:
            allConcerts:
              $ref: '#/components/links/concertsLink'
      x-swagger-router-controller: Concerts
  /login:
    summary: S'authentifier comme administrateur
    post:
      tags:
      - Administration
      summary: S'authentifier comme administrateur du service
      description: Seuls les administrateurs peuvent s'authentifier pour l'instant
      operationId: ""
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/login_body'
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: Administration
components:
  schemas:
    halLinkObject:
      required:
      - href
      type: object
      properties:
        href:
          type: string
          format: uri-template
        type:
          type: string
        deprecation:
          type: string
        name:
          type: string
        templated:
          type: boolean
          default: false
      example:
        templated: false
        name: name
        href: href
        type: type
        deprecation: deprecation
    concert-detail:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/halLinkObject'
        artist:
          type: string
        location:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
      example:
        date: 2000-01-23
        _links:
          key: null
        artist: artist
        description: description
        location: location
    concerts:
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/halLinkObject'
        concerts:
          type: array
          description: |
            # Ressources concerts
            Une longue description structurée en markdown sur le champ 'concerts (ajouter contexte)'
          items:
            $ref: '#/components/schemas/concert-detail'
      example:
        concerts:
        - date: 2000-01-23
          _links:
            key: null
          artist: artist
          description: description
          location: location
        - date: 2000-01-23
          _links:
            key: null
          artist: artist
          description: description
          location: location
        _links:
          key:
            templated: false
            name: name
            href: href
            type: type
            deprecation: deprecation
    login_body:
      required:
      - password
      - pseudo
      type: object
      properties:
        pseudo:
          type: string
          default: ed
        password:
          type: string
          default: astrongpassword
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  links:
    concertsLink:
      operationId: getAllConcerts
