/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DmoDesignFirstDuServiceWebDeBilletterieDeConcerts);
  }
}(this, function(expect, DmoDesignFirstDuServiceWebDeBilletterieDeConcerts) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HalLinkObject', function() {
      beforeEach(function() {
        instance = new DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.HalLinkObject();
      });

      it('should create an instance of HalLinkObject', function() {
        // TODO: update the code to test HalLinkObject
        expect(instance).to.be.a(DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.HalLinkObject);
      });

      it('should have the property href (base name: "href")', function() {
        // TODO: update the code to test the property href
        expect(instance).to.have.property('href');
        // expect(instance.href).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property deprecation (base name: "deprecation")', function() {
        // TODO: update the code to test the property deprecation
        expect(instance).to.have.property('deprecation');
        // expect(instance.deprecation).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property templated (base name: "templated")', function() {
        // TODO: update the code to test the property templated
        expect(instance).to.have.property('templated');
        // expect(instance.templated).to.be(expectedValueLiteral);
      });

    });
  });

}));
