/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ConcertDetail from './ConcertDetail';
import HalLinkObject from './HalLinkObject';

/**
 * The Concerts model module.
 * @module model/Concerts
 * @version 0.0.1
 */
export default class Concerts {
  /**
   * Constructs a new <code>Concerts</code>.
   * @alias module:model/Concerts
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Concerts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Concerts} obj Optional instance to populate.
   * @return {module:model/Concerts} The populated <code>Concerts</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Concerts();
      if (data.hasOwnProperty('_links'))
        obj.links = ApiClient.convertToType(data['_links'], {'String': HalLinkObject});
      if (data.hasOwnProperty('concerts'))
        obj.concerts = ApiClient.convertToType(data['concerts'], [ConcertDetail]);
    }
    return obj;
  }
}

/**
 * @member {Object.<String, module:model/HalLinkObject>} links
 */
Concerts.prototype.links = undefined;

/**
 * # Ressources concerts Une longue description structurée en markdown sur le champ 'concerts (ajouter contexte)' 
 * @member {Array.<module:model/ConcertDetail>} concerts
 */
Concerts.prototype.concerts = undefined;

