/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The LoginBody model module.
 * @module model/LoginBody
 * @version 0.0.1
 */
export default class LoginBody {
  /**
   * Constructs a new <code>LoginBody</code>.
   * @alias module:model/LoginBody
   * @class
   * @param pseudo {String} 
   * @param password {String} 
   */
  constructor(pseudo, password) {
    this.pseudo = pseudo;
    this.password = password;
  }

  /**
   * Constructs a <code>LoginBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginBody} obj Optional instance to populate.
   * @return {module:model/LoginBody} The populated <code>LoginBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginBody();
      if (data.hasOwnProperty('pseudo'))
        obj.pseudo = ApiClient.convertToType(data['pseudo'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} pseudo
 * @default 'ed'
 */
LoginBody.prototype.pseudo = 'ed';

/**
 * @member {String} password
 * @default 'astrongpassword'
 */
LoginBody.prototype.password = 'astrongpassword';

