/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DmoDesignFirstDuServiceWebDeBilletterieDeConcerts);
  }
}(this, function(expect, DmoDesignFirstDuServiceWebDeBilletterieDeConcerts) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Concerts', function() {
      beforeEach(function() {
        instance = new DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.Concerts();
      });

      it('should create an instance of Concerts', function() {
        // TODO: update the code to test Concerts
        expect(instance).to.be.a(DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.Concerts);
      });

      it('should have the property links (base name: "_links")', function() {
        // TODO: update the code to test the property links
        expect(instance).to.have.property('links');
        // expect(instance.links).to.be(expectedValueLiteral);
      });

      it('should have the property concerts (base name: "concerts")', function() {
        // TODO: update the code to test the property concerts
        expect(instance).to.have.property('concerts');
        // expect(instance.concerts).to.be(expectedValueLiteral);
      });

    });
  });

}));
