/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DmoDesignFirstDuServiceWebDeBilletterieDeConcerts);
  }
}(this, function(expect, DmoDesignFirstDuServiceWebDeBilletterieDeConcerts) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LoginBody', function() {
      beforeEach(function() {
        instance = new DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.LoginBody();
      });

      it('should create an instance of LoginBody', function() {
        // TODO: update the code to test LoginBody
        expect(instance).to.be.a(DmoDesignFirstDuServiceWebDeBilletterieDeConcerts.LoginBody);
      });

      it('should have the property pseudo (base name: "pseudo")', function() {
        // TODO: update the code to test the property pseudo
        expect(instance).to.have.property('pseudo');
        // expect(instance.pseudo).to.be(expectedValueLiteral);
      });

      it('should have the property password (base name: "password")', function() {
        // TODO: update the code to test the property password
        expect(instance).to.have.property('password');
        // expect(instance.password).to.be(expectedValueLiteral);
      });

    });
  });

}));
