/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import HalLinkObject from './HalLinkObject';

/**
 * The ConcertDetail model module.
 * @module model/ConcertDetail
 * @version 0.0.1
 */
export default class ConcertDetail {
  /**
   * Constructs a new <code>ConcertDetail</code>.
   * @alias module:model/ConcertDetail
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ConcertDetail</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConcertDetail} obj Optional instance to populate.
   * @return {module:model/ConcertDetail} The populated <code>ConcertDetail</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ConcertDetail();
      if (data.hasOwnProperty('_links'))
        obj.links = ApiClient.convertToType(data['_links'], {'String': HalLinkObject});
      if (data.hasOwnProperty('artist'))
        obj.artist = ApiClient.convertToType(data['artist'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Object.<String, module:model/HalLinkObject>} links
 */
ConcertDetail.prototype.links = undefined;

/**
 * @member {String} artist
 */
ConcertDetail.prototype.artist = undefined;

/**
 * @member {String} location
 */
ConcertDetail.prototype.location = undefined;

/**
 * @member {String} description
 */
ConcertDetail.prototype.description = undefined;

/**
 * @member {Date} _date
 */
ConcertDetail.prototype._date = undefined;

