/*
 * Démo Design-first du service web de billetterie de concerts
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.63
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The HalLinkObject model module.
 * @module model/HalLinkObject
 * @version 0.0.1
 */
export default class HalLinkObject {
  /**
   * Constructs a new <code>HalLinkObject</code>.
   * @alias module:model/HalLinkObject
   * @class
   * @param href {String} 
   */
  constructor(href) {
    this.href = href;
  }

  /**
   * Constructs a <code>HalLinkObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HalLinkObject} obj Optional instance to populate.
   * @return {module:model/HalLinkObject} The populated <code>HalLinkObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new HalLinkObject();
      if (data.hasOwnProperty('href'))
        obj.href = ApiClient.convertToType(data['href'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('deprecation'))
        obj.deprecation = ApiClient.convertToType(data['deprecation'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('templated'))
        obj.templated = ApiClient.convertToType(data['templated'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} href
 */
HalLinkObject.prototype.href = undefined;

/**
 * @member {String} type
 */
HalLinkObject.prototype.type = undefined;

/**
 * @member {String} deprecation
 */
HalLinkObject.prototype.deprecation = undefined;

/**
 * @member {String} name
 */
HalLinkObject.prototype.name = undefined;

/**
 * @member {Boolean} templated
 * @default false
 */
HalLinkObject.prototype.templated = false;

